### ISSUE TITLE
Add IRC_NICKSERV_SERVICE, IRC_NICKSERV_PASS to readthedocs

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#103]
### Issue
The [teleirc readthedocs](https://teleirc.readthedocs.io/en/latest/installation/#configuration) page explains what each of the configurations do in the `env.example` config file. However, there are two examples missing. `IRC_NICKSERV_SERVICE`, and `IRC_NICKSERV_PASS`.

### Solution
We need to describe what these options are used for.

**Comment by jwflory** [comment]
@Tjzabel just closed this in #104! :clapper:
