### ISSUE TITLE
Allow user to configure more variables for IRC server connection (e.g. port, SSL certs, etc.)

### ISSUE THREAD

**Issue by alcir** [RITlug/teleirc#113]
# Summary

Allow user to configure more parts of the IRC server connection (e.g. server port, using self-signed TLS certs, etc.)

# Background

IRC servers are a wild world. Everyone can do things a little bit differently or deploy their network in a different way. Most of the current developers run the bot on Freenode, so we haven't thought about other bots as much. However, to make the bot more useful for more people, more options should be opened up for configuration for those who need it.

# Details

Implementation should be straightforward. New env variables should be created for the following:

* IRC server port
* Allow expired / self-signed TLS certificates

These env variables should be used when negotiating the connection to the IRC server, instead of using hard-coded defaults. For our purposes, we can ship the Freenode defaults in our `env.example` file.

# Outcome

More people can use the bot on a range of different IRC networks, outside of only Freenode

---

_Original comment_:

There is a way to specify IRC server port as well as SSL self signed certificate or turning on debug in the .env file or as environment variables?

**Comment by alcir** [comment]
I mean the variables you can see in ```node_modules/irc/lib/irc.js```

**Comment by jwflory** [comment]
@alcir Currently there is not a way to specify these things in Teleirc. This is a good candidate issue for v1.4. We'll review issues for the next sprint once v1.3 is released.

**Comment by jwflory** [comment]
_Discussed in 2019-03-02 developer meeting._

---

This ticket was accepted for the v1.4 sprint.

We agreed this is a high-priority feature because it makes the bot more useful for more people. The implementation should be straightforward. I plan to work on this during the March sprint.

**Comment by jwflory** [comment]
Uhh, actually @Tjzabel meant to close issue 112 with that commit, not this PR. Reopening.

**Comment by Tjzabel** [comment]
@jwflory thanks for the catch!

**Comment by jwflory** [comment]
_Discussed in 2019-03-30 Teleirc developer meeting._

---

I plan to do research this week for this ticket. I hope to have an idea of what to include and change for this by the next developer meeting on April 6th. I hope to have a final implementation by April 13th. I left the final week open in case of delays before the end of the v1.4 window on April 20th.

**Comment by jwflory** [comment]
_Discussed during 2019-04-06 developer meeting._

---

I have no major updates yet. Still planning to get this done in the next week.

**Comment by jwflory** [comment]
I'm caught up in some of our other work for our new logo and planning our presence at the [Imagine RIT festival](https://www.rit.edu/imagine/) this month. I suspect I will not have time to work on this before the end of the Spring 2019 semester, but I will try to do what I can.

**Comment by Tjzabel** [comment]
@jwflory thanks for the update! The end of the semester really is a messy time :rofl:

**Comment by jwflory** [comment]
_Discussed in 2019-04-13 Teleirc developer meeting._

---

As discussed above, I chose to drop this ticket for this sprint since I need more bandwidth to prepare for Imagine RIT at the end of this month.

@nic-hartley finished #19. Next, he is researching this ticket to see if it is simple enough for him to work on before the end of the v1.3.1 sprint on Saturday, April 20th. If it is a quick fix, we'll get it into this release. If not, we'll push back to v1.4.

**Comment by jwflory** [comment]
_Discussed in 2019-04-20 developer meeting. Final developer meeting of the RIT Spring 2019 semester._

---

This ticket is dropped for the v1.3.1 sprint because we lacked team bandwidth to work on it leading up to university final exams. This ticket may be completed over the summer. More sprints may be planned for summer.

**Comment by jwflory** [comment]
See issue #145 from @diegoraf for the `ident` and `realname` fields set by the Node IRC library we use. It provides defaults of `nodebot` and `nodeJS IRC client` respectively, but we should override these and make them available to configure in our `env.example` file.

Also, when we do this, I would like to make our provided default config use `teleirc` for the `ident` and maybe `TeleIRC bot (https://github.com/RITlug/teleirc)` as the `realname` to make our project easier to find if someone doesn't care what these values are.

**Comment by Tjzabel** [comment]
Taken care of in PR #150 :tada: :tada:

**Comment by jwflory** [comment]
#150 addresses some of this issue, but not all of it. Before closing this issue, I would also like to hit these parts from [`irc.Client`](https://node-irc.readthedocs.io/en/latest/API.html#client):

* `userName`
* `realName`
* `secure`

I think these last configuration options, combined with #150, will be sufficient to address most users' needs.

**Comment by Tjzabel** [comment]
@jwflory I have a history of closing issues before fully realizing if they're done. I'll try to be better about that :smile:

**Comment by jwflory** [comment]
@Tjzabel No worries. I am equally guilty of doing the same at times too. :joy:

**Comment by jwflory** [comment]
@RITlug/teleirc-developers-commit-access Any thoughts on this from a v2.0.0 perspective?

**Comment by Tjzabel** [comment]
@jwflory I think having feature parity with where we currently stand is good enough. What other specific IRC features are part of the closing criteria? If they don't take a lot of time to implement, I am okay with adding this to the v2.0 release

**Comment by jwflory** [comment]
* _Metadata edited_:
    * **Milestone** (`v2.x.x` :arrow_right: `v2.1.0`)

**Comment by jwflory** [comment]
_Discussed in [2020-10-11 meeting](https://youtu.be/A5T_kpCdysw)._

---

I'm going to work on this one for this sprint. This will be my first code contribution to the v2 branch, and first time really getting into Go… so let's see where this goes. :wink:

**Comment by jwflory** [comment]
Fixed in Pull Request #355.

**Comment by jwflory** [comment]
@alcir Keep an eye out for this feature in v2.1.0 coming within the next week.
