### ISSUE TITLE
Community using teleirc

### ISSUE THREAD

**Issue by alcir** [RITlug/teleirc#114]
Organization: l.u.ma.ca. (Linux Users Massa Carrara)
Website: https://www.lumacaonline.org/
Telegram group URL: https://t.me/joinchat/Afu_TAczLfB4dQRKeYQCqg
IRC Channel: #lumaca on irc.autistici.org

Thanks

**Comment by Tjzabel** [comment]
@alcir I've created PR #116 

Feel free to look over it to make sure all the info is correct, otherwise this will most likely get pulled in by the end of the day.
