### ISSUE TITLE
Support for multiple systemd services (teleirc@.service file)

### ISSUE THREAD

**Issue by thenaterhood** [RITlug/teleirc#123]
Systemd has builtin support for a service file to back multiple services (see systemd-nspawn for an example). If we're supporting running multiple teleirc instances concurrently from the same box with systemd, we should add similar support so there's no need to copy around the teleirc service file.

This would also make it easier on people running instances, since updating the bot only involves one service file.

**Comment by Tjzabel** [comment]
This could be a good addition for those running teleirc for multiple communities.

**Comment by jwflory** [comment]
Is this something we still want for v2.0.0? Does it make sense with the container use case (#193)?

**Comment by Tjzabel** [comment]
@jwflory From v2.0 onwards, I don't think we should support systemd services as a viable deployment option. Thoughts?

**Comment by jwflory** [comment]
@Tjzabel Given we are focused more intently on the container use case, I agree. I'm going to close this issue out in favor of focusing our time on #193. :clapper: 

Thanks @thenaterhood for the suggestion anyways! If we were spending more time on v1.x.x, this would still be valid.
