### ISSUE TITLE
QoL Improvements

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#130]
### What this is
These are a collection of some quick quality of life improvements that don't necessarily warrant waiting for the 1.4 release. Items may or may not be added.

- [x] Show filetype IRC-side when `sendDocument=false`.
- [x] Insert ZWP into joining + leaving usernames Telegram-side.
- [x] (Backend) -- Work on handling promise rejections.

**Comment by jwflory** [comment]
_Discussed in 2019-03-30 Teleirc developer meeting._

---

@Tjzabel has more free time this week to look at this. He is targeting completion for the next developer meeting on Saturday, April 6th.

**Comment by Tjzabel** [comment]
As a side note with this issue, we should work on handling promises. 
```
(node:31990) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at TgDocumentHandler._GetDocumentMessage (/home/tim/Code/teleirc/lib/TelegramHandlers/TgDocumentHandler.js:62:13)
    at TgDocumentHandler.RelayDocumentMessage (/home/tim/Code/teleirc/lib/TelegramHandlers/TgDocumentHandler.js:37:28)
(node:31990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31990) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Tjzabel** [comment]
### Update
As we have our latest Teleirc Developers Meeting today, here are my updates with this issue:

* Wasn't actually able to get to this issue as I said I was :slightly_frowning_face: 
* I have a few ideas in terms of how I should go with getting this issue completed
  * Since this is a QoL issue, I *may* continue adding action items throughout the rest of the semester here.
  * Therefore, I am still determining scope and size of this issue.

**Comment by jwflory** [comment]
_Discussed during 2019-04-06 developer meeting._

---

>     * [ ]  Show filetype IRC-side when `sendDocument=false`.
>     * [ ]  (Backend) -- Work on handling promise rejections.

@Tjzabel has low bandwidth for the remaining semester. We decided the best strategy is to accomplish each of these one week at a time. For now, Tim will get either one of the two above improvements in as a pull request by the next developer meeting on Saturday, April 13 2019.

**Comment by Tjzabel** [comment]
## Update
I was able to get to inserting ZWP into joining/parting usernames. Due to this, test fails, so I will be adding those tests before adding the short PR.

**Comment by jwflory** [comment]
_Discussed in 2019-04-20 developer meeting. Final developer meeting of the RIT Spring 2019 semester._

---

@Tjzabel will try to wrap up the ZWP clean-up by Sunday night, April 21. On Monday, April 22, we will cut v1.3.1 either way. Future work will be pushed into the summer or next fall semester.

**Comment by jwflory** [comment]
PR #139 brings this issue to a wrap. :clapper: Thanks @Tjzabel for getting this in before the v1.3.1 release deadline! :tada:
