### ISSUE TITLE
Consider switching back to npm instead of yarn

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#136]
We decided to use `yarn` instead of `npm` for some reason a while back.

It may be a good idea to investigate this further, and figure out if we should switch back to the standard npm.

**Comment by Tjzabel** [comment]
I don't personally see any issues with yarn, and since we're using it, we may as well stick with it. 

My only reason for using npm, is the `npm audit` functionality npm gives to see if there are any current security vulnerabilities in any npm packages we pull in. Whether it's worth switching back to npm just for this functionality is up for discussion.

**Comment by jwflory** [comment]
@Tjzabel For now, we can keep this issue on the backlog. I think `npm` is easier for some deployment situations, but this is definitely a low-hanging fruit task. If someone submits a PR for us with this change, we can review it then.

**Comment by Tjzabel** [comment]
@jwflory I definitely agree this is a very low-hanging fruit task/change. I am honestly also fine with closing it out as well. I mostly made this issue so we could have a quick discussion at some point in the future about why we're actually using yarn instead of npm.

**Comment by Tjzabel** [comment]
Since we use yarn, I see no reason to go back to npm unless something breaks :man_shrugging:

**Comment by jwflory** [comment]
Yeah. I think this is a fair conclusion. :+1: I don't know if I understand the value in doing this either.
