### ISSUE TITLE
Quick Fix: Revert IRC bold formatting

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#143]
The use of markdown in order to achieve the bold formatting across platform has the unintended side-affect of messing with links that get sent across the bridge as well. 

Since URLs are quite important, we feel it would be a good idea to revert this change until we can figure out a more proper way to implement the bold formatting.

**Comment by Tjzabel** [comment]
@jwflory What are your thoughts on this issue?

**Comment by Tjzabel** [comment]
Since I haven't gotten any feedback on this issue, I am considering closing it in favor of working on #142 instead.

**Comment by jwflory** [comment]
@Tjzabel Given @xforever1313's suggestion to only process Markdown formatting on usernames, we can close this. Admittedly it still presents problems for usernames with certain characters (i.e. `jwf[m]` is rendered as `jwfm`, but I suppose this is workable for now.

Closing this as `wontfix` in favor of #142.
