### ISSUE TITLE
Add BSD Ar Community

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#144]
From @DiegoDAF:

> We are using teleirc on BSD Ar Group
> 
> Organization: BSD Argentina
> Website: http://sysarmy.com/bsdar
> Telegram group URL: https://t.me/bsdar
> IRC Channel: #bsdar on freenode.net

**Comment by Tjzabel** [comment]
@DiegoAF It seems I am unable to reach your website http://sysarmy.com/bsdar. Sysarmy.com works just fine, however. Is there another link that I should use?

**Comment by Tjzabel** [comment]
@DiegoDAF It seems I am unable to reach your website http://sysarmy.com/bsdar. Sysarmy.com works just fine, however. Is there another link that I should use?

**Comment by DiegoDAF** [comment]
Hi! yes, we are working on it, we are a spinof sysarmy (the argentinian sysadmins community) . In this dsays we are online again!

**Comment by Tjzabel** [comment]
@DiegoDAF okay, I will go ahead and add that link even though it's not currently online. If this changes in the future, feel free to create another issue for it.

**Comment by Tjzabel** [comment]
Merged through ^.^

**Comment by jwflory** [comment]
@DiegoDAF Thanks for letting us know about your community! :tada: 

@Tjzabel Thanks for taking care of this. :+1:
