### ISSUE TITLE
contributing guidelines link on README does not work

### ISSUE THREAD

**Issue by nlMeminger** [RITlug/teleirc#147]
the link in the repo README for contributing guidelines does not lead anywhere.

**Comment by jwflory** [comment]
@Tjzabel I notice you self-assigned this issue. Are you working on this one currently?

**Comment by Tjzabel** [comment]
@jwflory I was planning on doing it since it is such a quick fix. If you get to it before me, feel free to pick it up. I'm going to unassign myself from this issue since I am not actively working on this.
