### ISSUE TITLE
teleirc does not "crash" if it encounters a fatal error

### ISSUE THREAD

**Issue by thenaterhood** [RITlug/teleirc#15]
teleirc does not crash and return an exit code if it encounters an unrecoverable error. Rather, it fails and hangs without exiting.

**Comment by jflory7** [comment]
Is this something we want to target for the 1.1.0 release?

**Comment by thenaterhood** [comment]
Huh, thought I emailed in a reply to this but I guess it didn't make it.

Anyways, no, I don't think so. This isn't a new bug and I don't think it's any sort of showstopper. The only implication of it is if you're using a process manager (e.g. systemd) then it can't tell when the bot has crashed to restart it.

**Comment by thenaterhood** [comment]
Nah. I wouldn't say this is a deal breaker for us, and it isn't new.

The implication of this is that some things like systemd can't tell if the
bot needs to be restarted due to a crash. Putting out a patch later once we
track this down should be fine.
