### ISSUE TITLE
Make sure document sending is disabled by default

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#158]
Through a quick conversation on `#ritlug-teleirc`, someone mentioned their API key was being sent through when sending over a document. 

This feature was turned off by default, so I would like to double check to make sure this is actually working as intended. Document sending should only be done in channels where the owners feel it is okay for their key to be seen. 

## Steps to close this issue
1. Do a fresh clone of teleIRC
2. `cp env.example .env`
3. Update channel info in `.env`
4. Run teleIRC
5. Send over a document from Telegram
6. Make sure document does *not* make it over the bridge

**Comment by jwflory** [comment]
The option is disabled in the example configuration file:

https://github.com/RITlug/teleirc/blob/108b84dd6ec855997710603d403b16e87c9445b2/env.example#L13

I don't have a record of this conversation. Did we ask the person to check what version of TeleIRC they were running? Without more data or someone willing to confirm this, I suggest closing this as `invalid`. I think it is more likely they were running an outdated version of TeleIRC.

**Comment by Tjzabel** [comment]
At this point, I am okay with closing this issue.
