### ISSUE TITLE
RIT FOSS and TeleIRC Telegram channels don't show username bolding on IRC

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#160]
Since TeleIRC has rolled out username bolding, most channels now have username bolding from Telegram => IRC. I've noticed for some time that these two channels don't actually have bolding for some reason. 

I'm not sure if this is an issue with our current Ansible deployment, or some other reason.

**Comment by Tjzabel** [comment]
So this issue was *apparently* an issue on my side. 

When using a Matrix client, I was not getting any username bolding coming from Telegram, but after some configuration on my side, I see it :man_shrugging:

**Comment by jwflory** [comment]
@Tjzabel Weird! Thanks for updating us in this issue. :+1:
