### ISSUE TITLE
Find New Developer Meeting Time + Place

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#161]
With the summer hiatus coming to a close, it's time for us to work on finding a new meeting time and place to pick up the fall development sprint.

**Comment by Tjzabel** [comment]
Time has been set!

TeleIRC developer meeting time will be **Saturdays at 3pm EST**.

**Comment by jrtechs** [comment]
I can help reserve the MAGIC center room for the meeting.

**Comment by jrtechs** [comment]
This is the booking summary for the meeting room. We were unable to book 2 of the weeks in October.

Saturday, September 7, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, September 14, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, September 21, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, September 28, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, October 12, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, October 19, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, November 2, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, November 9, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, November 16, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, November 23, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, November 30, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
Saturday, December 7, 2019
3:00 PM - 4:00 PM TeleIRC team (Web Request) 071 MSS-3190 Conference Room
As-Is for 12
