### ISSUE TITLE
Add option for logging

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#162]
_Related to #213._

---

TeleIRC does not currently log output to a file. 

For those who run TeleIRC via methods like ansible which do not have direct access to TeleIRC's output, it would be helpful to have a log file that catches any output. This would allow for deeper debugging if/when issues arise.

**Comment by jwflory** [comment]
This would also be useful with monitoring infrastructure. It would be nice to leverage journalctl priorities for easy filtering.

Also, it might be worth adding functionality to write channel/group chat logs to disk, as a feature disabled by default.

**Comment by Tjzabel** [comment]
Hmm... I suppose we could add a feature to allow logging chats to disk. I would only consider it as an option disabled by default, as logging any sort of communication brings in additional considerations.

I agree it would be nice to allow for some sort of additional journalctl logging capabilities when using the systemd service files.

**Comment by Tjzabel** [comment]
## Update
If using the TeleIRC systemd service file, or docker image, then logging will go to `stdout`. 

This issue is more for logging to files.

**Comment by jwflory** [comment]
Provided the conversations we have had in our developer meetings and the on-going discussion in #213, I think it is acceptable to close this issue as `wontfix`. Using `stdout` is sufficient based on our supported deployment method of containers. It makes sense to use other tools to obtain the logs from the container itself.

Closing. :clapper:
