### ISSUE TITLE
Drop priority labels from TeleIRC issues

### ISSUE THREAD

**Issue by jwflory** [RITlug/teleirc#164]
# Summary

Delete "`priority:*`" labels from TeleIRC issue labels

# Background

These labels use a subjective method of establishing priority. There is no consistent way to determine what priority something is: it is up to the person who applies the label. Instead, there should be a greater emphasis on using the project boards to define priorities by sprint cycle.

Currently, I do not think the labels are useful anyways.

# Details

1. Delete priority labels from TeleIRC labels
2. Stick to using columns in project board as an indicator of developer priority

# Outcome

* More consistent around assigning how important an issue/task is by actual work being done
* Reducing complexity of how TeleIRC uses issue/PR labels

**Comment by Tjzabel** [comment]
Hmm.. I'm generally a heavy user of priority labels, but I completely understand the subjective nature of them. I am okay with moving away from using these labels, in favor of more descriptive labels and project board(s) usage.

**Comment by jwflory** [comment]
@Tjzabel Most/all of our other labels serve clear purposes. Can you think of other useful label / metadata changes, or does what we have now work? Now is a good time to suggest any improvements :smile:

**Comment by Tjzabel** [comment]
@jwflory by more descriptive, I simply meant making sure the labels adequately signify the importance of the issue, alongside the project board placement.

I don't think we need to necessarily create new label types in order to complete this issue. Just making sure the labels assigned adequately signify its current status.

**Comment by Tjzabel** [comment]
I decided to take this issue upon myself.

All priority labels have been removed from issues, and I am going to remove the priority label tags from the list of available options.

**Comment by jwflory** [comment]
@Tjzabel Thanks for jumping on this!
