### ISSUE TITLE
Research Go IRC Library

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#175]
Before we can develop out the IRC bot, we need to settle on an IRC library to use. Some options:

* [fluffle/goirc](https://github.com/fluffle/goirc)
* [thoj/go-ircevent](https://github.com/thoj/go-ircevent)
* [go-irc/irc](https://github.com/go-irc/irc)

**Comment by jwflory** [comment]
Here are [my notes](https://docs.google.com/document/d/1O0dQJofo4b_7CpRhm4HH1XKxA7bWcEuYeurgSM5z4AA/edit?usp=sharing) on the existing Go IRC libraries. I looked at five different libraries and narrowed it down to two, suggesting [lrstanley/girc](https://github.com/lrstanley/girc) as our choice.

**Comment by jwflory** [comment]
We agreed on `girc` for the IRC library in our developer meeting. Closing as complete. :clapper:
