### ISSUE TITLE
Determine which test suite to use

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#178]
Before we can truly continue with the Go rework, we need to determine which model of testing we should use. 

@Zedjones has offered some examples of how we should move forward with this

**Comment by Zedjones** [comment]
There are quite a few options in the testing space for Golang. For example, here are some possible combinations:

[Testify](https://github.com/stretchr/testify) is a pretty good standalone solution, used in combination with the `testing` package from the standard library. 

[Goblin](https://github.com/franela/goblin) combined with [gomock](https://github.com/golang/mock) is another good solution, especially for those used to Node BDD-style tests. You can see an example of what that might look like [here](https://github.com/Zedjones/redirectprotect/blob/master/internal/time_checking_add_checks_test.go). 

Keep in mind that there is no real "elegant" solution to testing in Golang, simply a matter of which solution is the least inelegant.

**Comment by Tjzabel** [comment]
We have decided to go with Testify for the moment!
