### ISSUE TITLE
Fix Go module bug introduced in #174

### ISSUE THREAD

**Issue by Zedjones** [RITlug/teleirc#182]
Since I was developing in my $GOPATH, I didn't realize that the module was set up incorrectly. Specifically, I was importing `"github.com/caarlos0/env"` instead of `"github.com/caarlos0/env"`. Also, `godotenv` was not automatically included in the `go.mod`.

**Comment by Tjzabel** [comment]
Fixed via 1717c1fc42afb12f1d8687b6d5e0aa4dc6dfb349
