### ISSUE TITLE
Create initial IRC bot using Config Settings

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#189]

**Comment by Zedjones** [comment]
For this task, I made the following changes: 
- Wrote a function to create a new client, which contains a girc client and our IRCSettings
- Wrote a method implementation on this client to adds a global handler and a handler when the client is connected to join the specified channel
- Wrote a method implementation on this client to start the bot, which currently calls the function to add handlers and runs the connect loop continuously (currently not concurrent)

**Comment by Tjzabel** [comment]
done!
