### ISSUE TITLE
Add unit tests to validate main TeleIRC bot

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#191]
At this point, we need to start creating unit tests for config parsing (if needed), and the main TeleIRC file.

**Comment by Tjzabel** [comment]
This is an ongoing effort.

We are still deciding on the best way to lay out our Go code for the most effective testing. This requires us to lay out our explicit function dependencies, and making sure we either move function dependencies to interfaces, or into the parameters.

**Comment by jwflory** [comment]
@Tjzabel will follow up in this issue.

Some code excerpts related to what we discussed on the developer call today:

https://github.com/RITlug/teleirc/blob/ddd980ac4ade0e75b044f9f1ce6e389d34cff173/internal/handlers/telegram/telegram_test.go#L11-L19

https://github.com/RITlug/teleirc/blob/ddd980ac4ade0e75b044f9f1ce6e389d34cff173/internal/handlers/irc/irc_test.go#L28-L29

**Comment by Tjzabel** [comment]
Since we have decided that the main `teleirc.go` file is nothing but a shell calling other functions/files we've written (where all the testing would actually be), I am okay with marking this issue as closed.

The comment above falls in line with the external dependencies issue, and I don't believe is directly related to writing unit tests for the main TeleIRC entrypoint.
