### ISSUE TITLE
Determine new developer workflow

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#194]
## Things we need to determine
* How developers build and test TeleIRC
  * Should we create a custom IRC and Telegram group for testing purposes?
* Should local deployment be done via Docker/Docker compose/minishift/bare metal?

**Comment by jwflory** [comment]
> * How developers build and test TeleIRC

Running a unit test suite should be enough as a minimum requirement for testing local changes.

>  * Should we create a custom IRC and Telegram group for testing purposes?

No. The TeleIRC dev chat is intended to be used for experimental purposes. We can instruct someone how to test locally in an existing IRC channel and group if they want to verify their changes. If we want to test a PR, we should update the git branch of the TeleIRC dev chat for experimenting.

> * Should local deployment be done via Docker/Docker compose/minishift/bare metal?

Personally I think Docker Compose works well for local development. It has a low barrier to entry compared to some k8s/OpenShift tools. I think we should keep the bar low with something like Docker Compose once we are happy with our container image again (#193).

**Comment by Tjzabel** [comment]
I agree with the above. This is another issue I think would fit well in the `docs/dev/` directory as a small subset of documentation.

**Comment by jwflory** [comment]
Do you mean like a "Project workflow" doc?

**Comment by Tjzabel** [comment]
I think since we already have the high level docs in the CONTRIBUTING.md, and the results of this issue (from what you said above) are roughly what we have documented, this issue may be safe to close. 

I *was* thinking of a "project workflow" doc of some sort, but since we already have the contributing guidelines, I'm not sure it's necessary to have. What are your thoughts?

**Comment by jwflory** [comment]
@Tjzabel I think an underlying problem is we publish two different docs in two different places (Sphinx and CONTRIBUTING.md); consolidating our contributing guidelines into the same place as our actual docs should make the process of contributing (and what that looks like) clear. I could take this action item on to consolidate our docs.
