### ISSUE TITLE
Determine new CI platform

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#196]
Before we build out the new CI for TeleIRC Go, we need to decide on a CI platform. Some options:
* TravisCI (current)
* ~DroneCI~
  * Good, but requires hosted runners
* GitHub Actions
  * Native to GitHub (we have beta access!)
* [GolangCI](https://golangci.com/)
  * Used with podman

**Comment by xforever1313** [comment]
I've had good luck with AppVeyor for my projects.  It *looks* like they support go: https://www.appveyor.com/docs/lang/go/

**Comment by Tjzabel** [comment]
@xforever1313 hm, thanks for the recommendation :+1:

**Comment by jwflory** [comment]
I'm curious, what was the problem case for this issue? Is there a specific reason or motivation to switch off of Travis CI?

**Comment by Tjzabel** [comment]
With the switch to Go, I thought it might make sense to explore alternative CI platforms. There's honestly no pure reason, so I am going to close this issue :+1:
