### ISSUE TITLE
Research Unified Telegram/IRC Event Format

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#198]
Both IRC and Telegram need to know the event format of the other bridge.

We should create a unified interface/struct for each side to use, so the other side knows what type of event is being sent over the bridge.

**Comment by Tjzabel** [comment]
I think this is something we have sufficiently researched.

This issue will be ongoing from now on, but I feel this is safe to close out.

**Comment by jwflory** [comment]
@Tjzabel Could you please leave a summary of any research / notes you have in this issue?

**Comment by Tjzabel** [comment]
(This shouldn't have been closed, why'd I gotta go and do that)

@jwflory I haven't actually looked into this issue sufficiently. Me and @Zedjones did some whiteboarding on how we can integrate IRC and Telegram several weeks ago, but I don't think we ended up writing in stone how to do that. 

Now that we have the base IRC and Telegram bridges set up to receive new messages, we can now go ahead and start implementing event handlers (after a few unit tests Telegram-side). We haven't sat down yet to figure out, with how we ended up setting up each side, the best way to send events to each other as they are properly handled. 

This is a good issue to now discuss on Sunday, if we end up having a meeting then.

**Comment by Tjzabel** [comment]
@Zedjones whenever you have the time, I would appreciate if you could do a little writeup on what your thoughts are with passing events between the bridge, since you seem to have a better mental handle on the specifics than I do.

**Comment by jwflory** [comment]
This is probably a good issue to review in our next dev meeting this Saturday.

**Comment by Tjzabel** [comment]
Here is the outcome of our discussions on how to best create the unfiied structure:
```Go
(...)
tgClient, _ := tg.NewClient(settings.Telegram)
tgChan := make(chan error)

ircClient := irc.NewClient(settings.IRC)
ircChan := make(chan error)

go ircClient.StartBot(ircChan, tg.SendMessage)
go tgClient.StartBot(tgChan, irc.SendMessage)
(...)
```

**Comment by Tjzabel** [comment]
Research is done. Continuing issue progress in #212
