### ISSUE TITLE
Build concurrency into the initialization of the IRC bot

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#199]
As it stands right now, after calling `irc.StartBot()`, nothing will run afterwards, as it is an ongoing function call. We need to fix this so it utilizes something like channels, so we can continue onto the next function call while it is running.

**Comment by Zedjones** [comment]
In addition to adding concurrency to the bot (the StartBot function now utilizes a channel), I also added a basic function to send a string message to the channel.

**Comment by Tjzabel** [comment]
Complete via #200
