### ISSUE TITLE
Feature request: filter messages starting with a prefix

### ISSUE THREAD

**Issue by MonkeyDo** [RITlug/teleirc#201]
An IRC channel I use for work has a bot set up to log all messages except the ones starting with a specific prefix (`[off]`), for privacy concerns.

Currently, that is stopping us from using TeleIRC, as we don't want those messages logged elsewhere.

A feature to filter outgoing messages that start with a prefix would be greatly appreciated (hopefully not just for our use-case) and fairly easy to implement.

I'm happy to open a PR if you are interested in this feature.

**Comment by jwflory** [comment]
To follow up here, @thenaterhood added this feature in #340. This is on target for an upcoming v2.1.0 release of TeleIRC.

I know this is a feature that the MusicBrainz community was looking for, so going to tag some folks here: @Freso @rdswift @Zastai @paurieraf
