### ISSUE TITLE
Create initial message handlers

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#205]
## Deliverables
* General Handler interface
* Function implementing said interface
```Go
type Handler interface {
    Handle(...)
}
```

### Create For
- [x] Telegram
- [X] IRC

## Blocking issues

The following issues block closing this issue. Once all issues below are closed, this issue may be closed.

- [x] #212

**Comment by Zedjones** [comment]
So I think doing something like this
```Go
type Handler = func(*girc.Client, girc.Event)
```
would make a lot more sense, instead of having a wrapping type/interface

**Comment by jwflory** [comment]
#240 was merged. It closes this issue. :clapper:
