### ISSUE TITLE
Create Join/Part Handlers

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#206]
TeleIRC needs to be able to monitor when users join and leave a channel or group, and send that message over to the other platform. This specific issue 

- [x] Create handlers to monitor joining/parting messages on Telegram

**Comment by jwflory** [comment]
@Tjzabel If you have a chance to expand this issue, please update the original comment with more info on what this ticket's success criteria look like. :slightly_smiling_face:

**Comment by Tjzabel** [comment]
@jwflory honestly, it's literally that, but I can update the comment to say "create for IRC and Telegram" :sweat_smile:

**Comment by jwflory** [comment]
_[Discussed in 2020-03-14 meeting](https://bluejeans.com/s/O5ssq/)._

---

@Tjzabel moved this over from `in progress` back to the current sprint. He swapped priority to focus on #238 since it is blocking future handlers.

**Comment by Tjzabel** [comment]
I've had a chance to work on this issue. AFAIK I will be able to put up a PR by the end of tomorrow (Friday). I am going to look into writing tests before I submit the PR.

**Comment by jwflory** [comment]
@Tjzabel Based on the edit, sounds like this ended up being an ambitious task. Do you think you will get a PR for this by our Saturday developer meeting?
