### ISSUE TITLE
Document a standard TeleIRC Go function design

### ISSUE THREAD

**Issue by jwflory** [RITlug/teleirc#207]
# Summary

From the discussions around testing, document the TeleIRC best practices for creating functions so they can be easily tested later

# Background

For our developer documentation, it would be useful to publish a few of our thoughts / notes on writing good functions that can be easily tested later. This will make it easier for us to adhere to a more standard style of programming and help new contributors in the future pick up best practices faster.

# Details

This discussion is still in progress, but @Tjzabel is going to write a new proposal (as a Markdown file) to improve our developer docs. The discussion can start here or as a new pull request to our docs.

# Outcome

Maintainer best practices / knowledge are documented to help new contributors get involved and make good contributions the first time

**Comment by Tjzabel** [comment]
@jwflory Hmm... Where would the best place to post these docs be?

**Comment by jwflory** [comment]
@Tjzabel I was thinking we start a category of "Developer docs" at a new directory at `docs/dev/`. The actual content could take any format that makes sense to us.

Sometimes for smaller projects, I like to write a collection of short howto-style articles until patterns or groupings emerge in the docs over time. For example, you could create `docs/dev/howto-write-functions.md` and explain the recommended way to write functions and explain why we write them that way.

Does this explanation make sense?

**Comment by Tjzabel** [comment]
@jwflory makes sense! I'll add some docs there :+1:

**Comment by jwflory** [comment]
After reviewing older issues, I think this is actually a duplicate of #73. Function design is important, but I think it is one part of a bigger discussion around code style. Also as @thenaterhood noted, defining a code style guide would allow us to set up automated linting in our CI farther down the line.

Closing as `duplicate`, let's move discussion over to #73. :clapper:
