### ISSUE TITLE
Determine if unit tests require functions to have explicit dependencies 

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#210]
We need to make sure all Go functions we create follow the standard of keeping all external dependencies referenceable from the function signature.

This will give us an easier time writing unit tests, where we can more effectively mock objects going into our functions.

**Comment by Tjzabel** [comment]
This may also require us to create interfaces to support this new design layout.

**Comment by jwflory** [comment]
## Why do this?

Easier to mock and instantiate in tests, as dependencies are passed in method signatures.

## Closing criteria

IRC code needs to be refactored to follow this design convention. Future code should be written with this design convention in mind.

- [ ] @Zedjones Refactor IRC code to have explicit dependencies
- [ ] @jwflory Add design convention for dependencies into docs (once we conclude on a way to do this)

**Comment by Tjzabel** [comment]
I renamed this issue to fall more in-line with our next testing sprint. The goal of having explicit dependencies within function signatures was to allow for better ease of testing. We need to determine if this is, in fact, an architecture design we need.

**Comment by Tjzabel** [comment]
I am going to close this issue in favor of #236 

This issue has been an ongoing discussion for quite a while, and we are not quite sure if this is even necessary to implement. The research we discover from our current testing sprint will determine our project layout.
