### ISSUE TITLE
Allow toggle for ZWP for Telegram usernames sent to IRC

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#224]
# Summary

Some platforms treat zero-width spaces as a normal space. It would be nice to support a toggle for such platforms.

# Background

**Is your improvement related to a problem? Please describe**:

When bridging TeleIRC across platforms that already have bridges set in place, sometimes the ZWP can be treated as a regular space, which is annoying to users.

**Describe the solution you'd like**:

We should add a boolean to the existing `ResolveUserName` and `GetFullUserName` methods within `lib/TelegramHandlers/TgHelpers.js`. 

**Describe alternatives you've considered**:

No other feasible alternatives.

# Details

Next steps are:
1. Add toggle in `env.example` for allowing/disallowing ZWP
2. Add toggle into `config.js` 
3. Add `enabled` boolean into methods listed above

# Outcome

Users who suffer from platforms that view ZWP as an actual space are able to view usernames normally again, at the expense of possibly pinging themselves (why ZWP was added).

**Comment by jwflory** [comment]
> Some platforms

It seems like this is from specific behavior you noticed. Since there are only two platforms (IRC and Telegram), I assume you mean Telegram?

**Comment by Tjzabel** [comment]
@jwflory I'm referring to external platforms that are being bridged to either IRC or Telegram.

In one case, someone was bridging their IRC channel to a Minecraft server, which displays all ZWP's coming from the IRC chat. We want to make a toggle so users in these cases are able to see messages fine.

**Comment by jwflory** [comment]
This is a late follow-up, but… given there are other tools like Matterbridge that exist for complex bridging situations, like a Minecraft server, I think we should defer users to those tools if going beyond IRC and Telegram is important. When we decided on the v2.0 release, we wanted to prioritize the things that make our TeleIRC project unique: fast, lean, lightweight, and working.

While a config option to toggle this is fairly minor and doesn't ask a lot, generally I want to avoid adding complexity that for perhaps 95% of use cases, isn't needed. It's not a problem now, but I have seen other projects with massive config files (like Matterbridge) and it makes set-up more difficult when you have to read through a bunch of docs to figure out what does what.

**Comment by Tjzabel** [comment]
@jwflory I'm wondering (for the `go-port`), if we should *not* use a ZWP?

I think we need to write up a pros/cons list on the benefits of the ZWP addition, before we can move forward with deciding to toggle this option or not.

**Comment by jwflory** [comment]
@Tjzabel Are there any alternatives other than the ZWP character? Also, we could implement this only for messages sent from Telegram to IRC, and not vice-versa. Telegram doesn't have the issue that IRC does with double-pinging.

**Comment by Tjzabel** [comment]
@jwflory I almost want to say we should either only include the ZWP from Telegram => IRC, or just not include it at all.

**Comment by jwflory** [comment]
@Tjzabel I prefer the first option. :wink:

**Comment by aNullValue** [comment]
I'm giving this a thumbs-up (and wish I could give it many more), because multiple of my users on IRC (not using platforms/bridges out from it) have complained about the existing behavior. Even I use an IRC client that displays the character as a regular space (weechat). I'm told that irssi does as well, but I haven't done any testing.

**Comment by jwflory** [comment]
Based on discussion in IRC today (2020-04-27 @ 16:50 ET), this issue was bumped up as a non-release blocking feature for v2.0.0. It is targeted for v2.0.0 but will not block us cutting a release on 23 May. If it misses, it will be targeted for a v2.1 release.

**Comment by jwflory** [comment]
_Discussed in [2020-05-23 meeting](https://bluejeans.com/s/kF2he)._

---

## Release-blocking: _YES_

@Tjzabel has this done in #322. It is pending a toggle setting to make it configurable. @Tjzabel and @Zedjones to collaborate on getting it merged later today.

**Comment by jwflory** [comment]
Implemented in #322. Merged. Closing as complete. :clapper:
