### ISSUE TITLE
Link to "Who uses TeleIRC" is broken

### ISSUE THREAD

**Issue by JoshuaMulliken** [RITlug/teleirc#226]
# Summary

The Link to "Who uses TeleIRC" is broken. It 404s

# Standard debugging steps

## Expected behavior

You should be able to go to Who uses TeleIRC

**Screenshots**:

## Stacktrace

```
paste logs here
```

# Other details

I've created a pull request: https://github.com/RITlug/teleirc/pull/225

**Comment by thenaterhood** [comment]
Resolved by #225. Thanks for your help! :)
