### ISSUE TITLE
Update Message State Diagram for girc library

### ISSUE THREAD

**Issue by jwflory** [RITlug/teleirc#233]
# Summary

Update [Message State Diagram](https://docs.teleirc.com/en/latest/dev/message-state-diagram/) to reflect recent development changes

# Background

@Zedjones mentioned on the development call that the IRC part of our state diagram is somewhat out-of-date because of how we interact with the `girc` library. It would be helpful to update the state diagram based on how things are currently working for on-boarding new developers!

# Details

The state diagram source is in my personal Lucidchart account. :see_no_evil: If @Zedjones can explain what changes need to be made, I can update the diagram and make a new PR to update it in our docs site.

# Outcome

* State Diagram accurately reflects current development decisions
* Easier for on-boarding new developers for understanding how messages travel through TeleIRC

**Comment by Zedjones** [comment]
So the only difference on the IRC side is that there is no "message object". Rather, handlers for each event type are registered with girc itself, and then girc handles the logic of choosing which handler to dispatch the event to.

**Comment by jwflory** [comment]
_Discussed in [2020-02-15 developer meeting](https://bluejeans.com/s/CQWYN/)._

---

I'm working on it today. PR coming soon.
