### ISSUE TITLE
Create Update Handler

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#238]
## Summary

In order to correctly assign Telegram Updates to their corresponding handlers, we need a top-level `updateHandler` to figure out what type of TG update is coming through, and properly hand off the update to the correct handler.

## Telegram Update Handler Overview

1. Receive an [Update](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/types.go#L29)
2. Parse the [Message](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/types.go#L133) type
    * If not a `Message` object, check for other `Update` types
3. Hand off action to the correct handler

**Comment by jwflory** [comment]
_[Discussed in 2020-03-14 meeting](https://bluejeans.com/s/O5ssq/)._

---

This is currently in progress. @Tjzabel is on the case. :sunglasses:
