### ISSUE TITLE
[Security] Telegram Bot Hash Leak

### ISSUE THREAD

**Issue by pragmatic-strain** [RITlug/teleirc#241]
# Summary

Data (bot hash) leak at IRC channel.

Example:
```
<teleirc_irc_bot_nick> 'Untitled Document' uploaded by telegram_user:
<teleirc_irc_bot_nick> https://api.telegram.org/file/bot523281407:AAGgJwVGwhX7XkQ-5SUKGahXe-yg6QfNWQU/animations/file_0.mp4
```
(Note: The above example of a bot hash was replaced and is no longer valid.)

## How to reproduce?

1. set `IRC_SEND_DOCUMENT=true` at `.env`
2. run teleirc
3. send video/mp4 to telegram group
4. See how teleirc leaks the Telegram bot hash to the irc channel

## Expected behavior

Should not leak bot hash under any circumstances. Please fix as you wish.

**Comment by Tjzabel** [comment]
First off, thanks for the issue :+1: 

## Background
This is actually an issue with the [Telegram Bot API](https://core.telegram.org/bots/api) itself. 
We (TeleIRC) disable sending over documents by default. You can see more history [here](https://github.com/RITlug/teleirc/issues/115).

## Potential Options
There are a few options I can think of:
1. Completely disable sending over documents
2. Look for an intermediary document hosting service like we do with Imgur
3. Reach out to Telegram and see if they have interest in changing this functionality
   * This would most likely break most bots out there that handle documents

**Comment by kennedy** [comment]
Not sure if this is helpful, but I found the API doc for uploading and downloading files for telegram: https://core.telegram.org/api/files

**Comment by jwflory** [comment]
Hi @pragmatic-strain, thanks for opening this. We won't address this for the v1.x.x release, but I opened a new issue (#242) for figuring out a better way to handle this in the v2.x.x release. I'm going to close this issue and we can keep up the discussion in #242.

> Not sure if this is helpful, but I found the API doc for uploading and downloading files for telegram: https://core.telegram.org/api/files

Thanks @kennedy, I edited this into the new issue! :+1:
