### ISSUE TITLE
Migrate existing print statements to use Go logging library

### ISSUE THREAD

**Issue by jwflory** [RITlug/teleirc#245]
# Summary

Migrate existing print statements to use Go's standard library for logging

# Background

**Is your improvement related to a problem? Please describe**:

Currently the only logging we use in the Go port are print statements.

**Describe the solution you'd like**:

Per #213, we should use the Go standard library for logging. This will give us more flexibility in verbosity levels and formatting later on.

**Describe alternatives you've considered**:

We considered `logrus` but decided to keep it simple and use the standard library to keep our dependencies down.

# Details

This is where I could find any existing use of print statements in our code:

```bash
$ grep --exclude-dir={docs/,.git/} -rnw . -i -e '.*print.*'

./cmd/teleirc.go:29:		fmt.Printf("Current TeleIRC version: %s\n", version)
./cmd/teleirc.go:35:		fmt.Printf("Debug mode currently set to: %t\n", *flagDebug)
./cmd/teleirc.go:40:		fmt.Fprintln(os.Stderr, err)
./cmd/teleirc.go:55:		fmt.Println(ircErr)
./cmd/teleirc.go:57:		fmt.Println(tgErr)
./internal/handlers/telegram/telegram.go:25:	fmt.Println("Creating new Telegram bot client...")
./internal/handlers/telegram/telegram.go:43:	fmt.Println("Starting up Telegram bot...")
./internal/handlers/telegram/telegram.go:47:		fmt.Println("Failed to connect to Telegram")
./internal/handlers/irc/handlers.go:47:		c.sendToTg(fmt.Sprintf(joinFmt, e.Source.Name))
./internal/handlers/irc/handlers.go:53:		c.sendToTg(fmt.Sprintf(partFmt, e.Source.Name))
./internal/handlers/irc/handlers.go:59:		c.sendToTg(fmt.Sprintf(quitFmt, e.Source.Name, e.Params[0]))
./internal/handlers/irc/irc.go:24:	fmt.Println("Creating new IRC bot client...")
./internal/handlers/irc/irc.go:45:	fmt.Println("Starting up IRC bot...")
./internal/handlers/irc/irc.go:68:	fmt.Println("Adding IRC event handlers...")
```

# Outcome

Consistent use of the Go library for logging where we are currently using print statements

**Comment by kennedy** [comment]
The `log` package is thread safe (yay goroutines). I think behind the scenes `log` writes a string via `os.pipe` into an virtual file/iowriter [`os.Stderr`, by default](https://golang.org/pkg/os/#pkg-variables).
I made a test go project `randomLogDemo`, to see how log writes into `os.Stdout` and `os.Stderr`. We cant use `logger.Panicln` or `logger.Fataln` because it would terminate the process regardless if it is writing to `os.Stdout`. Furthermore, not every log/print message is an error, thus `os.Stderr` would not be appropriate for ever log message type; we would need to seperate log messages into different topics of concerns. From the [DIY logging framework article](https://www.ardanlabs.com/blog/2013/11/using-log-package-in-go.html) during my research, we could create a `logger` object for each topic - `Info`, `Warning`, `Error`. I know we discuss a start-up flag (`-v`) to declare verbosity, this would be the foundation for that effort.

Let me know what you guys think. Once we come to agreement, @10eMyrT and I can start implimenting these and replace the above `fmt` locations, and we can all share the same logging practice

Proposed design:
```go
package main

import (
	"io/ioutil"
	"log"
	"os"
)

var (
	Info    *log.Logger
	Warning *log.Logger
	Error   *log.Logger
	Ignored *log.Logger
)

func main() {
	logFlags := log.Ldate | log.Ltime | log.Lmicroseconds | log.Llongfile
	Info = log.New(os.Stdout, "INFO: ", logFlags)
	Warning = log.New(os.Stdout, "WARNING: ", logFlags)
	Error = log.New(os.Stderr, "ERROR: ", logFlags)
	Ignored = log.New(ioutil.Discard, "ERROR: ", logFlags)

	Info.Println("Pushing string to Info")
	Warning.Println("Pushing string to Warning")
	Ignored.Println("Pushing string to Ignored")

	filename := "fakefile.txt"
	Info.Println("Attepting to Open", filename)
	_, err := os.Open(filename)
	if err != nil {
		Error.Println(err)
	} else {
		Info.Println("Reading", filename)
	}
}
```

```
INFO: 2020/02/23 18:13:35.202738 C:/Users/Kennedy/Documents/projects/randomLogDemo/logmenow.go:23: Pushing string to Info
WARNING: 2020/02/23 18:13:35.202738 C:/Users/Kennedy/Documents/projects/randomLogDemo/logmenow.go:24: Pushing string to Warning
INFO: 2020/02/23 18:13:35.202738 C:/Users/Kennedy/Documents/projects/randomLogDemo/logmenow.go:27: Attepting to Open fakefile.txt
ERROR: 2020/02/23 18:13:35.202738 C:/Users/Kennedy/Documents/projects/randomLogDemo/logmenow.go:31: open fakefile.txt: The system cannot find the file specified.
```

```go
package main

import (
	"log"
	"os"
)

func main() {
	logFlags := log.Ldate | log.Ltime | log.Lmicroseconds | log.Llongfile
	logger := log.New(os.Stdout, "", logFlags)
	logger.Panicln("Pushing string to Panicln") // Terminates and dumps memory trace
	logger.Fatalln("Pushing string to Fatalln") // Terminates
	logger.Println("Pushing string to Println")
}
```
```
2020/02/23 17:47:31.893368 C:/Users/Kennedy/Documents/projects/randomLogDemo/logmenow.go:11: Pushing string to Panicln
panic: Pushing string to Panicln


goroutine 1 [running]:
log.(*Logger).Panicln(0xc0000a8050, 0xc0000a5f40, 0x1, 0x1)
	C:/Go/src/log/log.go:226 +0xb1
main.main()
	C:/Users/Kennedy/Documents/projects/randomLogDemo/logmenow.go:11 +0xd9
```

**Comment by Tjzabel** [comment]
@kennedy thanks for the super in-depth update :+1: 

In terms of the different levels of logging, I think it would make sense for the command line argument to set the filter for what type of logging to output. The levels may be:
1. All (Info, Warning, Error)
2. Useful (Warning, Error)
3. Only what I need (Error)
4. I don't want any logs (Ignored)

Thoughts?

**Comment by 10eMyrT** [comment]
@kennedy Thanks for the research! Looks neat.
@Tjzabel Allowing command line definition is good, and I would suggest having option 1 as default.

**Comment by jwflory** [comment]
#254 from @10eMyrT was merged. Closing this issue as complete. :clapper:
