### ISSUE TITLE
Create Sticker Handler

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#249]
# Summary

TeleIRC v2.0 should handle Telegram stickers. 

# Background

**Is your feature request related to a problem? Please describe**:

If a Telegram user sends a sticker over to the channel, IRC users will not be able to understand context.

**Describe the solution you'd like**:

IRC users should be able to see when Telegram users send stickers.

**Describe alternatives you've considered**:

# Details

In the backend, all [Telegram stickers](https://core.telegram.org/bots/api#sticker) have an emoji attached to them. When a Telegram user sends a sticker, IRC users will interpret this sticker as the emoji attached to it. 

Closing criteria:
1. Sticker handler created
2. Sticker handler grabs emoji attached to sticker, and sends to IRC
3. Unit testing

# Outcome

IRC users see emojis when Telegram users send stickers.

**Comment by jwflory** [comment]
Hey @kennedy! We were wondering if you had a chance to look into this one yet. Do you think it's something we can keep on this sprint, or do you want to bump it back? If you need more time because of everything happening now, that's totally fine!

**Comment by kennedy** [comment]
Hey I have not looked at this yet, I think I need to bump it back. I definitely need more time

**Comment by jwflory** [comment]
@kennedy All good. I bumped this back to the next sprint. Thanks for updating us :+1: Hope everything is going well for you.

**Comment by kennedy** [comment]
im experiencing a blocker, cant seem to be able to trancode messages from telegram into irc. The GetUpdatesChan function is returning empty.

**Comment by kennedy** [comment]
> 
> 
> im experiencing a blocker, cant seem to be able to trancode messages from telegram into irc. The GetUpdatesChan function is returning empty.

... I figured it out. It was the privacy settings on the bot itself.
