### ISSUE TITLE
Add timeout to girc connect call

### ISSUE THREAD

**Issue by Zedjones** [RITlug/teleirc#253]
# Summary

Currently, if `girc.Connect` is called and the server is reached but never responds, then the goroutine will just hang forever. Using `girc.DialerConnect` instead, we can add a custom dialer which includes a timeout when connecting to the server.

# Background

**Is your improvement related to a problem? Please describe**:
`girc.Connect` can currently hang forever

**Describe the solution you'd like**:
We should add a timeout with a custom dialer.

# Details

# Outcome

**Comment by jwflory** [comment]
_[Discussed in 2020-03-14 meeting](https://bluejeans.com/s/O5ssq/)._

---

@10eMyrT is taking this on in the current sprint since #264 is blocked on #238. We figured this would be a good task to work on since the handlers need a little more time before we can full asynchronous on them.

**Comment by jwflory** [comment]
Fixed in #268. Closing! :clapper:
