### ISSUE TITLE
Add better error handling for config validation failures

### ISSUE THREAD

**Issue by Zedjones** [RITlug/teleirc#258]
# Summary

Currently, we just cast the error returned from the validator into a `validator.ValidationErrors` type and then return that as the error. However, this is clearly marked by the library as not intended for production. 

# Background

**Is your improvement related to a problem? Please describe**:
This improvement was inspired by @Tjzabel and others repeatedly accidentally setting the IRC channel field to #... without quotes and not getting an proper error output.

**Comment by jwflory** [comment]
#259 merged. Thanks for getting this @Zedjones! Closing as complete. :clapper:
