### ISSUE TITLE
Create TeleIRC v2.0.0-pre1, merge go-port into master

### ISSUE THREAD

**Issue by jwflory** [RITlug/teleirc#265]
_Discussed in #163 and [2020-03-14 meeting](https://bluejeans.com/s/O5ssq/)._

---

# Summary

Cut our first pre-release of TeleIRC v2.0.0 and move back to using a single `master` branch for development

# Background

After many, many months of steady but solid work, we are nearing the first Minimum Viable Product (MVP) of TeleIRC v2.0.0. When we started planning last August in #163, we were loosely committed to maintaining the v1.x.x release and while we were working on the Go port (#222, #225, #227). However, the landscape is different in March 2020!

I propose we make a firm commitment to end the development cycle for TeleIRC v1.x.x and cut a final release, v1.5.0 (see the [v1.5.0 milestones](https://github.com/RITlug/teleirc/milestone/9?closed=1) for tracked changes). By doing this, we make a firm commitment to completing and finishing the Go port of the project. While we are happy to continue supporting users running v1.x.x versions, we will not write new code for the Node version anymore.

Downstream users can always access and run the older versions by checking out the git tags for any of the v1.x.x versions, but we will not maintain a branch upstream in our repository. This should also help us avoid attracting contributors who think our project is primarily a Node project, since our default branch is the Node version (and thus, that is how our project appears across GitHub).

# Details

I propose this release process:

- [x] Create a new git tag on latest `master` branch
- [x] Cut a release on our _Releases_ page from `v1.5.0` git tag
- [x] Open a new pull request from `go-port` to `master`
- [x] Merge using a merge commit (this will need to be re-enabled in _Settings_)
- [x] Delete `go-port` branch
- [x] Shift all future development onto the now Go-based `master` branch

# Outcome

* All developer time from that point forward is fully committed to v2.x.x versions
* Less awkward workflow of maintaining two "active" branches at the same time (and no more periodic rebasing of `master` onto `go-port`)

**Comment by Tjzabel** [comment]
@jwflory looks good! Is there a timeframe you think would work best for completing this work? How should the current PR be handled?

**Comment by jwflory** [comment]
@Tjzabel I would like to do this either at the halfway point or the end of this sprint, hopefully when all open PRs are cleared. I noticed there is an open security vulnerability in the Node version, and @dependabot is going to make an automatic version bump sometime soon:

https://github.com/RITlug/teleirc/network/alert/yarn.lock/minimist/open

So, once we patch that CVE and clear through the existing queue of PRs, I think we can cut the v1.5.0 release and I can make the big PR to merge `go-port` into `master`.

**Comment by Zedjones** [comment]
I guess once we do this, we'll need to go through and look at the current issues we have open. That's the only thing I feel is really missing from this process, but otherwise things look good :+1:

**Comment by jwflory** [comment]
@Zedjones For the most part, I've kept up pretty well on triaging older issues and/or closing them out in favor of newer ones. I've also been using [release milestones](https://github.com/RITlug/teleirc/milestones) to group our existing issues into things we want for the v2.0.0 release, and things we want for future v2.x.x releases.

**Comment by jwflory** [comment]
#277 was The Big Merge™. It happened. We now have a `v2.0.0-pre1` release:

https://github.com/RITlug/teleirc/releases/tag/v2.0.0-pre1

It's not production-ready yet, but we should be able to gradually work towards running this in our developer chat room soon. We can talk about that in our meeting tomorrow.

Closing this issue as done. :clapper:
