### ISSUE TITLE
Fix unused vars and unchecked returns

### ISSUE THREAD

**Issue by jwflory** [RITlug/teleirc#266]
# Summary

Make CI tests pass again by fixing unused variables and unchecked returns

# Standard debugging steps

## How to reproduce?

Reproduced in our CI pipeline. See below:

https://travis-ci.org/github/RITlug/teleirc/jobs/662793390#L271

## Expected behavior

CI tests should pass.

## Stacktrace

```go
internal/handlers/telegram/handler.go:8:2: `joinFmt` is unused (varcheck)
	joinFmt = "%s (@%s) has joined the Telegram Group!"
	^
internal/handlers/telegram/handler.go:9:2: `partFmt` is unused (varcheck)
	partFmt = "%s (@%s) has left the Telegram Group."
	^
internal/config.go:99:29: Error return value of `validate.RegisterValidation` is not checked (errcheck)
	validate.RegisterValidation("notempty", validateEmptyString)
	                           ^
internal/handlers/telegram/telegram.go:35:13: Error return value of `tg.api.Send` is not checked (errcheck)
	tg.api.Send(newMsg)
	           ^
```

**Comment by Zedjones** [comment]
In regards to this error:
```go
internal/handlers/telegram/telegram.go:35:13: Error return value of `tg.api.Send` is not checked (errcheck)
	tg.api.Send(newMsg)
	           ^
``` 
It's a bit more complicated than might be initially obvious. During the call on 3/21, we agree that it would be best to check `tg.api.Send` for the error, log it, and retry sending a few times before giving up.
