### ISSUE TITLE
Remove CodeClimate from README

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#288]
As we've officially merged the `go-port` branch into master, we no longer have a use for CodeClimate. We should remove CodeClimate from our README documentation, and remove any hooks CC has in TeleIRC.

**Comment by jwflory** [comment]
I think CodeClimate is still useful for us, but we need to get it set up for Go. I did an initial setup in #291. A further iteration on this can also include automatic test coverage reports, so we can always know what the percentage of code tested is in the project.
