### ISSUE TITLE
Leave/join usernames are sent to the wrong channel

### ISSUE THREAD

**Issue by i5o** [RITlug/teleirc#31]
When using teleirc for two channels with 
> config.sendNonMsg = true;

if someone leaves channel1 in IRC, it would message channel1 mirror in Telegram, but also channel2 mirror in Telegram;
Steps to reproduce:
Config your bot to be in two channels
-> #sugar 
-> #poxip 

Supposing that you are in #sugar , leave in #sugar 
expected: teleirc to send a message to #sugar mirror in Telegram
result:
#sugar mirror in telegram the messages
but #poxip mirror get the message two.

config.js: https://paste.fedoraproject.org/494846/80617652/

**Comment by jflory7** [comment]
Hey @i5o, looking at this deeper, I think you are using another project with the same name (this [teleirc](https://github.com/FruitieX/teleirc)). Since it seems like it's for a different project, I'm going to close this issue. Sorry for the confusion here.
