### ISSUE TITLE
Send bot message after a successful version upgrade

### ISSUE THREAD

**Issue by jwflory** [RITlug/teleirc#318]
# Summary

When the bot restarts after a version change, emit a message in that chat such as "TeleIRC updated to v2.x.x!"

# Background

**Is your improvement related to a problem? Please describe**:

Upgrading the bots requires logging into IRC. If you are going to get a definite confirmation that the bot disconnects and reconnects, you have to see it from IRC.

**Describe the solution you'd like**:

To more transparently announce updates, a message could be sent when TeleIRC restarts after a successful upgrade:

`TeleIRC updated to v2.0.0-pre2!`

This would appear in IRC and Telegram.

**Describe alternatives you've considered**:

We could just put it in the logs. But I think it has two benefits to be a chat message and not a log message:

1. Better transparency to users about changes to software that processes their data (or, chat messages)
2. Subtle way to raise awareness for our project since a downstream user never has to reveal their bot uses RITlug/teleirc code

# Details

1. Research best way to manage version state (e.g. how do we detect version changes?)
2. Implement a version checker method that remembers version across two runs
2. Add version upgrade notice to logger
3. Announce version upgrade notice as a chat message in IRC and Telegram

# Outcome

1. Better awareness / user experience for managing TeleIRC versions
2. Better awareness for TeleIRC in downstream bots running our code

**Comment by Tjzabel** [comment]
@jwflory I see this issue as high maintenance, low reward. As of now, we do not have any way of managing state across deployments, and therefore don't have a way to keep track of which version TeleIRC was running on its last run. 

The only way I can (at the moment) see this as being possible, is if we had a function to disconnect and reconnect from TG/IRC, but that defeats the purpose of restarting the bot due to a version upgrade.

**Comment by xforever1313** [comment]
I actually did something similar on my [IRC Bot](https://github.com/xforever1313/Chaskis/tree/master/Chaskis/Plugins/NewVersionNotifier).

Tim is right, there needs to be some kind of persistence for this to work.  Chaskis works by:
* After joining a channel, it reads a ".lastversion.txt" file if it exists.
* If the file exists, it compares the current version of the bot with the version in the file.
* If they match, no messages get sent.
* If they do not match, the message gets sent to the channel(s), and the new version gets written to ".lastversion.txt".

**Comment by jwflory** [comment]
Looking back at this, I concur with @Tjzabel and @xforever1313. Since TeleIRC is sort of "stateless" by design, at least for now, I don't think this has a lot of value for the project.

We can always revisit later if things change… but for now, I am going to go ahead and close this issue out as out of scope. :city_sunset:
