### ISSUE TITLE
One should be able to see files / images shared from telegram

### ISSUE THREAD

**Issue by KevinMGranger** [RITlug/teleirc#33]

**Comment by jflory7** [comment]
I believe this is possible. I remember @repkam09 mentioned the possibility of doing it, but the files "expire" after some time, unless we were to upload them to another site or service, like Imgur for images.

**Comment by repkam09** [comment]
I wrote up a quick version of this which posts the link directly to the Telegram (temporary, 1 hour) version of the file. Having it upload somewhere more permanent would be good, but I'm not sure where that would be.

If you have a simple file repository on the RITLug servers that can be hit from our service here, maybe. I have done upload scripts using node and restify for my own personal projects. But then comes the issue of protecting that from random people uploading file, setting limits, deleting after some amount of time, etc.

**Comment by robbyoconnor** [comment]
TeleIRC (the other one) spins up a web server and hosts it on the server...

**Comment by mestaritonttu** [comment]
Why not join forces with the other teleirc? Is there some fundamental technological disagreement preventing such a merger?

**Comment by jflory7** [comment]
@mestaritonttu It was mostly that we created this project for our own community, then it ended up becoming a little bit popular, and we kept maintaining it. There's no disagreement, but more that we're just maintaining what we created and probably don't have the time to actively contribute to many more projects.

**Comment by xforever1313** [comment]
Created this pull https://github.com/RITlug/teleirc/pull/38 to get Telegram's URL to the uploaded photo.  Right now, it just posts the URL to the IRC channel, but as Mark said, that URL only lasts an hour.  But, we need to get the URL before we can do a more persistent solution.

**Comment by jflory7** [comment]
@xforever1313 Amazing! This is still a lot of progress. We could potentially try to link to an API for a site like Imgur to upload the photos and post that link instead. Will try to review the PR soon!

**Comment by Chris-Bitler** [comment]
The Imgur API for uploading images supports passing it a URL, so perhaps it could be passed the telegram URL? https://apidocs.imgur.com/#4b8da0b3-3e73-13f0-d60b-2ff715e8394f

**Comment by Chris-Bitler** [comment]
Just an update on this: I am working on implementing uploading images to imgur, but they have some bug with their API application registration that caused it to auto redirect away from the page; I was told by their support that this will be fixed on monday.

**Comment by Chris-Bitler** [comment]
I'm not sure how commenting did that.

**Comment by jflory7** [comment]
Oops, this issue is stale. @xforever1313 extracted the image via the Telegram API in #38 and @Chris-Bitler implemented support to upload pictures in Imgur in #39.

Thank you @xforever1313 and @Chris-Bitler! Closing as complete. :clapper:
