### ISSUE TITLE
Error al instalar version go

### ISSUE THREAD

**Issue by dorlanpabon** [RITlug/teleirc#351]
Hola, disculpad, estaba trabajando con la version node y todo iba bien, trata de instalar con go y me sale el siguiente error, ¿algun samaritano que sepa a que se debe?, lo estoy corriedno en openshift.

go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
--
  | go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
  | can't load package: package github.com/ritlug/teleirc: unknown import path "github.com/ritlug/teleirc": cannot find module providing package github.com/ritlug/teleirc
  | can't load package: package github.com/ritlug/teleirc: unknown import path "github.com/ritlug/teleirc": cannot find module providing package github.com/ritlug/teleirc
  | error: build error: non-zero (13) exit code from docker-registry.default.svc:5000/openshift/golang@sha256:ebfed97ee40d3e38794a12c10587082173e90546d2cb97514d7e42457ec156b7

**Comment by jwflory** [comment]
_Discussed in [2020-10-25 meeting](https://youtu.be/V4UaDtmRrfQ)_.

---

Hola @dorlanpabon. Entiendo el español. Pero la mayoría del equipo no. Si escribes en inglés, otros miembros del equipo también pueden ayudarte.

Tenemos algunas preguntas de seguimiento:

1. ¿Está utilizando su propio Dockerfile? ¿Cómo añadiste TeleIRC al contenedor?
1. ¿Puede compartir tu Dockerfile?
1. ¿Qué versión de Golang está utilizando?
1. ¿Qué versión de TeleIRC está utilizando?

No sé si lo viste. Pero tenemos un Dockerfile listo para el uso. ¿Lo intentaste?

https://github.com/RITlug/teleirc/tree/master/deployments/container

**Comment by dorlanpabon** [comment]
Hi jwflory, thanks, Use the container you had prepared.
it worked for me, in openshift.
Although I don't take the ".env", I had to manually strain the variables.

**Comment by jwflory** [comment]
Thank you for following up @dorlanpabon. Glad it works for you now! Please open a new issue if you find any other bug. 🙂
