### ISSUE TITLE
Here we are!

### ISSUE THREAD

**Issue by deltagnan** [RITlug/teleirc#357]
Name: mIRC Italia Crew
Telegram: https://t.me/mircitaliacrew
IRC Channel: https://webchat.freenode.net/#mircitaliacrew
Version: teleirc-2.1.0

**Comment by jwflory** [comment]
Hi @deltagnan, thanks for submitting your community 🥳  We'll work on getting the mIRC Italia Crew up on our docs.

If you have any feedback on the v2 release, feel free to upvote any open issues by adding a 👍🏻 or open a new issue if you have other feedback.

**Comment by deltagnan** [comment]
Hi @jwflory, it would be perfect if you could activate /names and /topic commands like FruitieX/teleirc :)
