### ISSUE TITLE
teleirc's v2.2.0 does not provide a binary relase breaking the 'teleirc-bin' AUR package.

### ISSUE THREAD

**Issue by da-edra** [RITlug/teleirc#379]
Hello!

I'm the maintainer of the [teleirc](https://aur.archlinux.org/packages/teleirc/) and the [teleirc-bin](https://aur.archlinux.org/packages/teleirc-bin/) packages in the Arch User Repository.

I was able to update the `teleirc` package to v2.2.0 without any issue as that package is directly built from source code however, the `teleirc-bin` package can't be updated to v2.2.0 because no Linux binary was provided as part of this release.

Even tho the `teleirc` package compiles pretty fast some users may prefer to download the `teleric-bin` package because that way the don't have to download the `go` package in order to compile the code.

Could you please provide a binary version of `teleirc` in future releases so I can keep maintaining the `teleirc-bin` package?

If providing binary releases is not on your roadmap it's totally fine. :)

**Comment by Tjzabel** [comment]
@da-edra TeleIRC binary should now be available in the 2.2.0 release. Please let me know if you have any further issues :+1:

**Comment by da-edra** [comment]
@Tjzabel Thank you so much for this! I've updated [teleirc-bin](https://aur.archlinux.org/packages/teleirc-bin) to v2.2.0!! 🥳
