### ISSUE TITLE
teleirc shows the telegram nicknames in the Telegram with unneeded space

### ISSUE THREAD

**Issue by kompilainenn** [RITlug/teleirc#390]
# Summary

teleirc shows the telegram nicknames in the Telegram with unneeded space

## How to reproduce?

1. go to into #libreoffice-qa in Libera Chat
2. go to into telegram channel https://t.me/LibreOffice_QA
3. try write in IRC my telegram nickname like @Kompilainenn and press enter there
4. look in the Telegram channel on the result. It will look as @K ompilainenn

## Expected behavior

teleirc should shows the telegram nicknames without any unneeded spaces inside

**Comment by jwflory** [comment]
I am going to close this issue per the previous comment 🎬  This can be resolved by changing the TeleIRC configuration to hide zero-width spaces.
