### ISSUE TITLE
To add the Russian community of LibreOffice

### ISSUE THREAD

**Issue by tagezi** [RITlug/teleirc#43]
I would like to know if you can help with the organization of communication between telegrams and irc.
We have two channels #libreoffice-ru on the freenode and libreofficeru in the telegrams. But we do not have a server to install the teleirc.
I know that you help community LibreOffice with some channals.
Is it possible for Russian part?
Thank you in advance.

**Comment by jflory7** [comment]
@tagezi Hi! The Document Foundation has a hosted server for Teleirc and can probably help you. Could you email guilhem@libreoffice.org and jwf@fedoraproject.org with your request? Thanks!
