### ISSUE TITLE
Fix "file_lines" issue in lib/TeleIrc.js

### ISSUE THREAD

**Issue by ritlug-root** [RITlug/teleirc#48]
File `TeleIrc.js` has 308 lines of code (exceeds 250 allowed). Consider refactoring.

https://codeclimate.com/github/RITlug/teleirc/lib/TeleIrc.js#issue_5aaa8799e65aaa0001000027

**Comment by jflory7** [comment]
This issues are handy, but not very useful. We can always check these kinds of things from the [CodeClimate dashboard](https://codeclimate.com/github/RITlug/teleirc/issues) for this project. I'm going to close this issue for now.
