### ISSUE TITLE
Fix "similar-code" issue in lib/TeleIrc.js

### ISSUE THREAD

**Issue by ritlug-root** [RITlug/teleirc#49]
Similar blocks of code found in 4 locations. Consider refactoring.

https://codeclimate.com/github/RITlug/teleirc/lib/TeleIrc.js#issue_5aaa879fe65aaa0001000036

**Comment by jflory7** [comment]
This issues are handy, but not very useful. We can always check these kinds of things from the [CodeClimate dashboard](https://codeclimate.com/github/RITlug/teleirc/issues) for this project. I'm going to close this issue for now.
