### ISSUE TITLE
Handle telegram bot rate limiting

### ISSUE THREAD

**Issue by thenaterhood** [RITlug/teleirc#5]
Telegram bots are rate limited:

* Less than 1 message per second
* No more than 20 messages per minute

When bridging IRC, this clearly becomes a problem in particularly active chats. The bot needs to understand the rate limits and batch messages in order to avoid hitting the limits. Ideally, this will make use of an intelligent algorithm which will do a batch-and-wait for large volumes of messages, but will immediately forward messages for lower message volumes. It also needs to do this in a way that doesn't result delays that are long or frequent enough to disrupt the chat.

**Comment by thenaterhood** [comment]
See #7

**Comment by jflory7** [comment]
Closed by #7.
