### ISSUE TITLE
multi-line messages should have each lined prefixed with the userid

### ISSUE THREAD

**Issue by michalrud** [RITlug/teleirc#53]
Currently, when a message with newlines is posted to Telegram, it will be automatically splitted by the bot (well, technically by the underlying irc client library), so when `user1` posts a message like this to Telegram (notice the newline):

```
This is my message.
<user2> I am not very smart
```

teleirc will post following messages to the IRC channel:

```
<teleirc>: <user1> This is my message.
<teleirc>: <user2> I am not very smart
```

Therefore, misleading other IRC users into thinking that `user2` admitted his/her own shortcomings.

I will be preparing a PR with a fix. The code is mostly ready, but I would like to test it more before I would consider it ready _enough_ as I didn't actually test it with telegram nor IRC.

**Comment by jflory7** [comment]
Thanks for reporting this, @michalrud. I see you have some work in your local branch for this feature. Let us know if you need any help testing the changes out – we have the Teleirc testing group to help us with this purpose. :slightly_smiling_face:

**Comment by michalrud** [comment]
Testing is the exact thing that's left to be done - I've written some unit tests and in sterile environment of UT it seems to work fine, but it would be great if you can take the code and check it in the testing group :)

**Comment by jwflory** [comment]
#95 was a duplicate, but I stole the title of that issue to update this one.
