### ISSUE TITLE
Community using teleirc

### ISSUE THREAD

**Issue by Dhanesh95** [RITlug/teleirc#59]
Organization: Hamara Linux
Website: https://hamaralinux.org
Telegram group URL: https://t.me/hamaraLinux
IRC Channel: #hamara on irc.oftc.net

**Comment by jwflory** [comment]
Thanks @Dhanesh95, I will work on doing this in the next week or so.

If you have some time, feel free to submit a PR too and add it into [this page](https://github.com/RITlug/teleirc/blob/devel/docs/who-uses-teleirc.rst) in the docs. The list is sorted alphabetically. :slightly_smiling_face:

**Comment by Dhanesh95** [comment]
On Wednesday 18 July 2018 08:03 PM, Justin W. Flory wrote:
> Thanks @Dhanesh95 <https://github.com/Dhanesh95>, I will work on doing
> this in the next week or so.
> 
> If you have some time, feel free to submit a PR too and add it into this
> page
> <https://github.com/RITlug/teleirc/blob/devel/docs/who-uses-teleirc.rst>
> in the docs. The list is sorted alphabetically. 🙂
> 

Sure! I'll be glad to send a PR. Will send one by the end of the week.

**Comment by DiegoDAF** [comment]
We are using teleirc on BSD Ar Group

Organization: BSD Argentina
Website: http://sysarmy.com/bsdar
Telegram group URL: https://t.me/bsdar
IRC Channel: #bsdar on freenode.net

**Comment by Tjzabel** [comment]
@DiegoDAF Thank you for your your addition! We generally prefer you open a new issue with your group info, but I'll take care of that for you.
