### ISSUE TITLE
Bring CodeClimate grade up to an A

### ISSUE THREAD

**Issue by robbyoconnor** [RITlug/teleirc#64]
This is **REALLY** great for beginners looking to get their feet wet who knows Node.js well and has good code design instincts. 

Currently [we are at a D](https://codeclimate.com/github/RITlug/teleirc) -- let's get it up!

**Comment by Tjzabel** [comment]
With commit 8931f1ae, we should slowly see an increase in the CC grade.

CodeClimate is being a little too strict, so we hope to loosen up some of its checks to improve this.

**Comment by robbyoconnor** [comment]
That's kind of the point. It's supposed to be strict -- it's running a
linter.

**Comment by Tjzabel** [comment]
I get that it is supposed to be strict, but it seems to be *overly* strict. We're testing out a threshold before CC declares code to be duplicates, which is where a lot of the issues seem to arise. 

If this doesn't work we can always revert to what it's been doing.

**Comment by robbyoconnor** [comment]
You can customize things -- Code Climate allows you to make calls on
your own :)

**Comment by jwflory** [comment]
@Tjzabel 30 lines over 25 lines feels like a harmless change. When I write code, I'm more liberal with breaking things across multiple lines anyways for the benefit of readability.

**Comment by robbyoconnor** [comment]
There are valid reasons for deviating from coding standards...do so with
good reason though.

**Comment by jwflory** [comment]
Since we are in the middle of rewriting the codebase (#163) and already have some issues open to discuss code style and best practices (#73, #207), I'm going to close this issue as `wontfix` for the time being. Once we ship the v2.0.0 release and figure out what tools we can use for code health, we can open a new issue to discuss this later.

Closing. :clapper:
