### ISSUE TITLE
Support for registering nicks

### ISSUE THREAD

**Issue by ct-martin** [RITlug/teleirc#66]
As we discovered in our (RITlug & FOSS@MAGIC) spam mitigation during the recent Freenode spam attacks, having bots with unregistered nicks can get them kicked from a channel. This issue requests support for a registered nick. Most likely this would take the form of:
* config values for the desired nick & NickServ password
* authenticating to NickServ when joining the server
* authenticating to NickServ any time NickServ challenges it

**Comment by jwflory** [comment]
Fortunately, @michalrud already took care of this in #65. I'll try to review this during the week.

**Comment by jwflory** [comment]
#65 was recently merged, thanks to the help of @michalrud. There are some unit tests remaining to be rewritten (#76), but this functionality is now supported. I'm closing this as completed. :clapper:
