### ISSUE TITLE
Bot should check API responsiveness upon startup

### ISSUE THREAD

**Issue by ponkyh** [RITlug/teleirc#81]
Had an issue when bot started just fine and joined the IRC channel but nothing got redirected from IRC to TG or vice versa. No errors. Tried to curl the api but got "curl: (35) Unknown SSL protocol error in connection to api.telegram.org:443", curling from the same host with --interface "different ip" worked, so I'd guess it's a some kind of rate limit/blacklist on Telegrams end.

Maybe the bot could do a /getMe API-call upon startup to check that API is actually responding? getMe response looks like this:

{"ok":true,"result":{"id":xxx,"is_bot":true,"first_name":"botnick","username":"botname"}}

**Comment by Tjzabel** [comment]
@jwflory @thenaterhood I'm assuming since the PR referencing this issue has been merged, that this issue has been fixed?

**Comment by thenaterhood** [comment]
In theory yeah
