### ISSUE TITLE
Fix Imgur Photo Uploading

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#93]
With #87 we've discovered imgur is not properly set up, and so therefore we get an error saying imgur is undefined.

In order to fix this, we need to implement proper Imgur photo uploading from Telegram to IRC. 
Here is my suggestion for how we move forward.

## Steps to get Imgur Working
1. Obtain Imgur API key.
2. Either add image uploading to `_UploadImage`, or implement `uploadUrl`.
3. Create test cases to test new implementation

#### Helpful links
*  [Imgur Uploading using JS + API key](https://ctrlq.org/code/20526-javascript-image-uploader)
* [Complete C implementation for further reading](https://git.xfce.org/apps/xfce4-screenshooter/tree/lib/screenshooter-imgur.c#n104)

**Comment by Tjzabel** [comment]
We may want to figure out a short-term change for #87, whether that be removing unused imgur calls, or commenting out the current unworking Imgur implementation.

**Comment by jwflory** [comment]
Per discussion with @xforever1313 tonight, easiest way to do this is likely to handle it in constructor of Imgur class and set the environment variable there.

**Comment by Tjzabel** [comment]
@jwflory yeah we'll need to set the client ID in the env file and then pass it into the Imgur class.

I'm working on the upload function, and should have it by the end of the week unless someone finishes it before me.

**Comment by jwflory** [comment]
@Tjzabel Awesome! If you're already working on, I will assign this issue to you. :+1:

**Comment by Tjzabel** [comment]
## Update
Imgur standalone implementation is just about complete. This takes in an Imgur API Client ID, and Telegram photo url as parameters, and uploads the file whilst returning the status code.

### Next Steps
1. See what information should be returned from the photo upload
2. Integrate standalone code into teleirc codebase
3. Write unit tests
4. ???
5. Profit!

**Comment by Tjzabel** [comment]
As a further mention, my implementation does not use the nodejs imgur library. 

Because the old implementation used this imgur library, I am going to revisit using this. However, I don't want to be bringing in more dependencies than necessary, so I won't be going into extensive testing with the old implementation unless I can get it to work relatively quickly.

**Comment by Tjzabel** [comment]
### ... I had a confusion
(I've just provisioned my own teleirc test bot to test out these issues)
In my infinite wisdom, I thought the imgur support was broken. After testing in my own environment, I have learned the opposite :smile: The imgur test cases fail, which had further confirmed my initial theory. 

## But now everything is all good!
It seems all we need to implement is the imgur client ID.

The client ID is the API key that is used to signal to imgur what application is making the calls. We should definitely be using the one in the `.env` file.

Also, the test cases are failing because the test images on RITlug's website (https://ritlug.com) do not contain these test images anymore. 

My realization makes this issue much easier and quicker to solve. I am going to update the above roadmap.

**Comment by Tjzabel** [comment]
Imgur photo uploading works.
