### ISSUE TITLE
Needs validation: does bot automatically restart when env file is hot-swapped while running?

### ISSUE THREAD

**Issue by jwflory** [RITlug/teleirc#94]
Recently, since I started to use Ansible to deploy the bot, I noticed that the bot appears to restart on its own when the `.env` file is replaced while the bot is running. Currently, I restart the bot after reloading the config (and unfortunately, if one updates, I'm restarting all of them :confused: ). But if I don't have to do this anymore… that would be awesome.

We need help from a willing tester to try and confirm this. A manual test should include both editing the file in place and also completely replacing the file with a new copy.

**Comment by Tjzabel** [comment]
@jwflory I can verify after manual testing that the configuration file is loaded **only at startup**.

Therefore, the bot will sadly need to be restarted each time the configuration changes.

**Comment by jwflory** [comment]
@Tjzabel Thanks for poking around at this one. I must have noticed a fluke. I'll close this issue as is. :clapper:
