### ISSUE TITLE
multi-line messages should have each lined prefixed with the userid

### ISSUE THREAD

**Issue by bexelbie** [RITlug/teleirc#95]
This will make the messages easier to understand on the irc side.

**Comment by Tjzabel** [comment]
@bexelbie I agree! This should be relatively simple to implement.

**Comment by jwflory** [comment]
Closing as a duplicate of #53. By the looks of it, @michalrud actually took a crack at it already, but I'm not sure if he is still working on it.

I'm going to steal the name of this issue and rename the other one, since I think this issue title is more clear.
